version: '3.1'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jogoteca
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3306:3306
